// <auto-generated />
using System;
using DevXpert.Modulo3.ModuloConteudo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevXpert.Modulo3.ModuloConteudo.Data.Migrations
{
    [DbContext(typeof(CursoContext))]
    [Migration("20251022025648_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AI")
                .HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DevXpert.Modulo3.ModuloConteudo.Domain.Aula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("bigint");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("Titulo", "CursoId")
                        .IsUnique()
                        .HasDatabaseName("UQ_TITULO_CURSO_AULAS")
                        .HasAnnotation("SqlServer:FillFactor", 80);

                    b.ToTable("Aulas", (string)null);
                });

            modelBuilder.Entity("DevXpert.Modulo3.ModuloConteudo.Domain.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("CargaHoraria")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("PermitirMatricula")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UQ_NOME_CURSOS")
                        .HasAnnotation("SqlServer:FillFactor", 80);

                    b.ToTable("Cursos", (string)null);
                });

            modelBuilder.Entity("DevXpert.Modulo3.ModuloConteudo.Domain.Aula", b =>
                {
                    b.HasOne("DevXpert.Modulo3.ModuloConteudo.Domain.Curso", "Curso")
                        .WithMany("Aulas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("DevXpert.Modulo3.ModuloConteudo.Domain.Curso", b =>
                {
                    b.OwnsOne("DevXpert.Modulo3.ModuloConteudo.Domain.ConteudoProgramatico", "ConteudoProgramatico", b1 =>
                        {
                            b1.Property<Guid>("CursoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Ementa")
                                .IsRequired()
                                .HasColumnType("varchar(1000)")
                                .HasColumnName("Ementa");

                            b1.Property<string>("Instrutor")
                                .IsRequired()
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Instrutor");

                            b1.Property<string>("PublicoAlvo")
                                .IsRequired()
                                .HasColumnType("varchar(250)")
                                .HasColumnName("PublicoAlvo");

                            b1.HasKey("CursoId");

                            b1.ToTable("Cursos");

                            b1.WithOwner()
                                .HasForeignKey("CursoId");
                        });

                    b.Navigation("ConteudoProgramatico");
                });

            modelBuilder.Entity("DevXpert.Modulo3.ModuloConteudo.Domain.Curso", b =>
                {
                    b.Navigation("Aulas");
                });
#pragma warning restore 612, 618
        }
    }
}
